config/routes.rb
Portifolie::Application.routes.draw do

  get "home/index"

  resources :pictures
  resources :projects
  resources :profiles
  resources :educations
  resources :experiences
  resource :session

  root :to => "home#index"
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  attr_accessible :title, :status, :website, :technologies, :description, :picture_relations_attributes 
 
  
  has_many :picture_relations, :as => :parent, :dependent => :destroy
  has_many :pictures, :through => :picture_relations
  
  validates_presence_of :title, :length => { :minimum => 3 }
  
  accepts_nested_attributes_for :picture_relations, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :check_authentication, :except => [:index, :show]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @pictures = Picture.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @pictures = Picture.in_relation_with(@project)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper  
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |project_form| %>
<% if @project.errors.any? %>
<div id="error_explanation">
	<button type="button" class="close" data-dismiss="alert">
		×
	</button>
	<h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

	<ul>
		<% @project.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="row-fluid">
	<div class="span5">
		<div class="field">
			<%= project_form.label :title %>
			<%= project_form.text_field :title %>
		</div>
		<div class="field">
			<%= project_form.label :status %>
			<%= project_form.select :status, ["Achieved","In Progress","Discarded"]%>
		</div>
		<div class="field">
			<%= project_form.label :website %>
			<%= project_form.text_field :website, :class => "giant_textarea" %>
		</div>
		<div class="field">
			<%= project_form.label :technologies %>
			<%= project_form.text_field :technologies, :class => "giant_textarea" %>
		</div>
	</div>

	<div class="span7">
		<div class="field">
			<%= project_form.label :description %>
			<%= project_form.text_area :description, :class => "giant_textarea" %>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span5">
		<div id="pictures">
			<%= render :partial => 'picture_relations/form', :locals => {:form => project_form} %>
		</div>
	</div>
	<div class="span7">
		<% if @pictures %>
		<div id="ImageList">
			<table class="table table-bordered">
				<caption>
					<h3>Wana add some Pictures?</h3>
				</caption>
				<tr>
					<th>Legend</th>
					<th>Picture</th>
					<th>Add</th>
					<th></th>
					<th></th>
				</tr>
				<% @pictures.each do |picture| %>
				<tr>
					<td><%= picture.legend %></td>
					<td><%= image_tag(picture.url, :width => 50) if picture.url.present? %></td>
					<td><%= link_to_add_picture(project_form, picture) %></td>
				</tr>
				<% end %>
			</table>
		</div>
		<% end %>
	</div>
</div>

<div class="actions">
	<%= project_form.submit :class => "btn btn-danger" %>
</div>
<% end %>

app/views/projects/edit.html.erb
<%= content_for :active_projects, "class=active" %>

<div class="page-header">
	<h1>Editing project</h1>
</div>
<article class="center">
	<%= render 'form' %>

	<%= link_to 'Show', @project, :class => "btn btn-info" %>
	<%= link_to 'Back', projects_path, :class => "btn" %>
</article>

app/views/projects/index.html.erb
<%= content_for :active_projects, "class=active" %>

<div class="page-header">
	<h1>Projects</h1>
</div>

<section class="accordion-container">
	<% @projects.each do |project| %>
	<div>
		<% if params[:project_id].present? and params[:project_id].to_i == project.id %>
		<input id="ac-<%= project.id %>" name="accordion-1" type="checkbox", checked="checked" />
		<% else %>
		<input id="ac-<%= project.id %>" name="accordion-1" type="checkbox" />
		<% end %>
		<label for="ac-<%= project.id %>"> <%= project.title %> </label>
		<article>
			<span><em class="bullet"></em> Status : <%= project.status %></span>
			<% if !project.website.blank? %>
			<span><em class="bullet"></em> Website : <a href="<%= project.website %>"><%= project.website %></a></span>
			<% end %>
			<% if logged_in? %>
			<span><em class="bullet"></em> <%= link_to 'Edit', edit_project_path(project) %></span>
			<span><em class="bullet"></em> <%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></span>
			<% end %>
			<%= simple_format(project.description) %>
			<h5>Technologies : <%= project.technologies %></h5>
			<% pictures = project.pictures %>
			<% if !pictures.blank? %>
			<div class="carousel-pictures">
				<div id="myCarousel<%= project.id%>" class="carousel slide">
					<!-- Carousel items -->
					<div class="carousel-inner">
						<% pictures.each_index do |e_index| %>
						<% if e_index == 0 %>
						<div class="active item">
							<%= image_tag(pictures[e_index].url) if pictures[e_index].url.present? %>
						</div>
						<% else %>
						<div class="item">
							<%= image_tag(pictures[e_index].url) if pictures[e_index].url.present? %>
						</div>
						<% end %>
						<% end %>
					</div>
					<% if pictures.count > 1 %>
					<!-- Carousel nav -->
					<a class="carousel-control left" href="#myCarousel<%= project.id%>" data-slide="prev">&lsaquo;</a>
					<a class="carousel-control right" href="#myCarousel<%= project.id%>" data-slide="next">&rsaquo;</a>
					<% end %>
				</div>
			</div>
			<% end %>
		</article>
	</div>
	<% end %>
</section>
<br />

<%= link_to 'New Project', new_project_path, :class => "btn" unless !logged_in? %>

app/views/projects/new.html.erb
<%= content_for :active_projects, "class=active" %>

<div class="page-header">
	<h1>New project</h1>
</div>
<article class="center">
	<%= render 'form' %>

	<%= link_to 'Back', projects_path, :class => "btn" %>
</article>

app/views/projects/show.html.erb
<%= content_for :active_projects, "class=active" %>
<% if notice %>
<div id="notice" class="alert alert-info">
	<button type="button" class="close" data-dismiss="alert">
		×
	</button>
	<%= notice %>
</div>
<% end %>
<article class="center">
	<div class="row-fluid">
		<div class="span5">
			<p>
				<b>Title:</b>
				<%= @project.title %>
			</p>

			<p>
				<b>Start date:</b>
				<%= @project.status %>
			</p>

			<p>
				<b>Website:</b>
				<%= @project.website %>
			</p>

			<p>
				<b>Description:</b>
				<%= simple_format(@project.description) %>
			</p>

			<p>
				<b>Technologies:</b>
				<%= @project.technologies %>
			</p>

		</div>
		<div class="span7">
			<table class="table table-bordered">
				<caption>
					<h3>Linked Picture :</h3>
				</caption>
				<tr>
					<th>Legend</th>
					<th>Picture</th>
				</tr>
				<% @project.pictures.each do |picture| %>
				<tr>
					<td><%= picture.legend %></td>
					<td><%= image_tag(picture.url, :width => 50) if picture.url.present? %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>

	<%= link_to 'Edit', edit_project_path(@project), :class=>"btn btn-danger"  unless !logged_in? %>
	<%= link_to 'Back', projects_path, :class=>"btn" %>
</article>