config/routes.rb
Portifolie::Application.routes.draw do

  get "home/index"

  resources :pictures
  resources :projects
  resources :profiles
  resources :educations
  resources :experiences
  resource :session

  root :to => "home#index"
  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  
  mount_uploader :url, PictureUploader
  
  has_many :picture_relations, :dependent => :destroy
  has_many :projects, :through => :picture_relations, :source => :parent, :source_type => 'Project'
  
  validates_presence_of :url
  
  scope :in_relation_with, lambda {|obj| where("id not in (select picture_id from picture_relations pr where parent_id = #{obj.id} AND parent_type = '#{obj.class.to_s}')")}
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_filter :check_authentication
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to pictures_url, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, :html => { :multipart => true }) do |f| %>
<% if @picture.errors.any? %>
<div id="error_explanation">
	<button type="button" class="close" data-dismiss="alert">
		×
	</button>
	<h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

	<ul>
		<% @picture.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :legend %>
	<br>
	<%= f.text_field :legend %>
</div>
<div class="field">
	<%= f.label :url %>
	<br>
	<%= f.file_field :url %>
</div>
<div class="actions">
	<%= f.submit 'Upload Picture', :class => "btn btn-success" %>
</div>
<% end %>

app/views/pictures/edit.html.erb
<%= content_for :active_pictures, "class=active" %>

<div class="page-header">
	<h1>Editing picture</h1>
</div>
<article class="center">
	<%= render 'form' %>

	<%= link_to 'Show', @picture, :class => "btn btn-info" %> |
	<%= link_to 'Back', pictures_path, :class => "btn" %>
</article>

app/views/pictures/index.html.erb
<%= content_for :active_pictures, "class=active" %>
<% if notice %>
<div id="notice" class="alert alert-info">
	<button type="button" class="close" data-dismiss="alert">x</button>
	<%= notice %>
</div>
<% end %>
<div class="page-header">
	<h1>Listing pictures</h1>
</div>

<article class="center">
	<table class="table table-bordered">
		<tr>
			<th>Legend</th>
			<th>Picture</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>

		<% @pictures.each do |picture| %>
		<tr>
			<td><%= picture.legend %></td>
			<td><%= image_tag(picture.url, :width => 80) if picture.url.present? %></td>
			<td><%= link_to 'Show', picture, :class => "btn btn-info" %></td>
			<td><%= link_to 'Edit', edit_picture_path(picture), :class => "btn btn-warning" %></td>
			<td><%= link_to 'Destroy', picture, confirm: 'Are you sure?', method: :delete , :class => "btn btn-danger" %></td>
		</tr>
		<% end %>
	</table>
	<br />
	<%= link_to 'New Picture', new_picture_path, :class => "btn"  unless !logged_in? %>
</article>

app/views/pictures/new.html.erb
<%= content_for :active_pictures, "class=active" %>

<div class="page-header">
	<h1>New picture</h1>
</div>
<article>
	<div class="row">
		<div class="span4"></div>
		<div class="span4">
			<%= render 'form' %>

			<%= link_to 'Back', pictures_path, :class => "btn" %>
		</div>
	</div>
</article>

app/views/pictures/show.html.erb
<%= content_for :active_pictures, "class=active" %>
<% if notice %>
<div id="notice" class="alert alert-info">
	<button type="button" class="close" data-dismiss="alert">x</button>
	<%= notice %>
</div>
<% end %>

<div class="page-header">
	<h1>Showing <%= @picture.legend %></h1>
</div>

<article class="center">
		<p>
			<b>Url:</b>
			<%= @picture.url %>
		</p>

		<p>
			<%= image_tag(@picture.url, :style => "max-width: 860px;") if @picture.url.present? %>
		</p>

		<%= link_to 'Edit', edit_picture_path(@picture), :class => "btn btn-danger"  unless !logged_in? %>
		<%= link_to 'Back', pictures_path, :class => "btn" %>
</article>