config/routes.rb
Portifolie::Application.routes.draw do

  get "home/index"

  resources :pictures
  resources :projects
  resources :profiles
  resources :educations
  resources :experiences
  resource :session

  root :to => "home#index"
  

end

app/models/education.rb
class Education < ActiveRecord::Base

  attr_accessible :school, :website, :location, :start_date, :end_date, :description, :keywords, :picture_relations_attributes 
 
  has_many :picture_relations, :as => :parent, :dependent => :destroy
  has_many :pictures, :through => :picture_relations
  
  validates_presence_of :school
  
  accepts_nested_attributes_for :picture_relations, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController

  before_filter :check_authentication, :except => [:index, :show]
  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @educations }
    end
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
    @education = Education.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/new
  # GET /educations/new.json
  def new
    @education = Education.new
    @pictures = Picture.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/1/edit
  def edit
    @education = Education.find(params[:id])
    @pictures = Picture.in_relation_with(@education)
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(params[:education])

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render json: @education, status: :created, location: @education }
      else
        format.html { render action: "new" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /educations/1
  # PUT /educations/1.json
  def update
    @education = Education.find(params[:id])

    respond_to do |format|
      if @education.update_attributes(params[:education])
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education = Education.find(params[:id])
    @education.destroy

    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |education_form| %>
<% if @education.errors.any? %>
<div id="error_explanation">
	<button type="button" class="close" data-dismiss="alert">
		×
	</button>
	<h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

	<ul>
		<% @education.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row-fluid">
	<div class="span5">
		<div class="field">
			<%= education_form.label :school %>
			<%= education_form.text_field :school %>
		</div>
		<div class="field">
			<%= education_form.label :website %>
			<%= education_form.text_field :website %>
		</div>
		<div class="field">
			<%= education_form.label :location %>
			<%= education_form.text_field :location %>
		</div>
		<div class="field">
			<%= education_form.label :keywords %>
			<%= education_form.text_field :keywords, :class => "giant_textarea" %>
		</div>
	</div>

	<div class="span7">

		<div class="field">
			<%= education_form.label :description %>
			<br />
			<%= education_form.text_area :description, :class => "giant_textarea" %>
		</div>
	</div>
</div>

<div class="field">
	<%= education_form.label :start_date %>
	<%= education_form.date_select :start_date %>
</div>
<div class="field">
	<%= education_form.label :end_date %>
	<%= education_form.date_select :end_date %>
</div>

<div class="row-fluid">
	<div class="span5">
		<div id="pictures">
			<%= render :partial => 'picture_relations/form', :locals => {:form => education_form} %>
		</div>
	</div>
	<div class="span7">
		<% if @pictures %>
		<div id="ImageList">
			<table class="table table-bordered">
				<caption>
					<h3>Wana add some Pictures?</h3>
				</caption>
				<tr>
					<th>Legend</th>
					<th>Picture</th>
					<th>Add</th>
					<th></th>
					<th></th>
				</tr>
				<% @pictures.each do |picture| %>
				<tr>
					<td><%= picture.legend %></td>
					<td><%= image_tag(picture.url, :width => 50) if picture.url.present? %></td>
					<td><%= link_to_add_picture(education_form, picture) %></td>
				</tr>
				<% end %>
			</table>
		</div>
		<% end %>
	</div>
</div>

<div class="actions">
	<%= education_form.submit :class => "btn btn-danger" %>
</div>
<% end %>

app/views/educations/edit.html.erb
<%= content_for :active_educations, "class=active" %>
<div class="page-header">
	<h1>Editing education</h1>
</div>

<article class="center">
	<%= render 'form' %>

	<%= link_to 'Show', @education, :class => "btn btn-info" %>
	<%= link_to 'Back', educations_path, :class => "btn" %>
</article>

app/views/educations/index.html.erb
<%= content_for :active_educations, "class=active" %>

<div class="page-header">
	<h1>Educations</h1>
</div>

<section class="accordion-container">
	<% @educations.each do |education| %>
	<div>
		<input id="ac-<%= education.id %>" name="accordion-1" type="checkbox" />
		<label for="ac-<%= education.id %>"> <%= education.school %> </label>
		<article>

			<span><em class="bullet"></em> Start : <%= education.start_date %></span>
			<span><em class="bullet"></em> End : <%= education.end_date %></span>
			<% if !education.website.blank? %>
			<span><em class="bullet"></em> Website : <a href="<%= education.website %>"><%= education.website %></a></span>
			<% end %>

			<% if logged_in? %>
			<span><em class="bullet"></em> <%= link_to 'Edit', edit_education_path(education) %></span>
			<span><em class="bullet"></em> <%= link_to 'Destroy', education, confirm: 'Are you sure?', method: :delete %></span>
			<% end %>
			
			<%= simple_format(education.description) %>
			
			<h5> Compétences : <%= education.keywords %> </h5>
			<% pictures = education.pictures %>
			<% if !pictures.blank? %>
			<div class="carousel-pictures">
				<div id="myCarousel<%= education.id %>" class="carousel slide">
					<!-- Carousel items -->
					<div class="carousel-inner">
						<% pictures.each_index do |e_index| %>
						<% if e_index == 0 %>
						<div class="active item">
							<%= image_tag(pictures[e_index].url) if pictures[e_index].url.present? %>
						</div>
						<% else %>
						<div class="item">
							<%= image_tag(pictures[e_index].url) if pictures[e_index].url.present? %>
						</div>
						<% end %>
						<% end %>
					</div>
					<% if pictures.count > 1 %>
					<!-- Carousel nav -->
					<a class="carousel-control left" href="#myCarousel<%= education.id%>" data-slide="prev">&lsaquo;</a>
					<a class="carousel-control right" href="#myCarousel<%= education.id%>" data-slide="next">&rsaquo;</a>
					<% end %>
				</div>
			</div>
			<% end %>
		</article>
	</div>
	<% end %>
</section>
<br />

<%= link_to 'New Education', new_education_path, :class => "btn" unless !logged_in? %>

app/views/educations/new.html.erb
<%= content_for :active_educations, "class=active" %>
<div class="page-header">
	<h1>New education</h1>
</div>
<article class="center">
<%= render 'form' %>

<%= link_to 'Back', educations_path, :class => "btn" %>
</article>

app/views/educations/show.html.erb
<%= content_for :active_educations, "class=active" %>

<% if notice %>
<div id="notice" class="alert alert-info">
	<button type="button" class="close" data-dismiss="alert">
		×
	</button>
	<%= notice %>
</div>
<% end %>
<article class="center">
	<div class="row-fluid">
		<div class="span5">
			<p>
				<b>School:</b>
				<%= @education.school %>
			</p>

			<p>
				<b>Website:</b>
				<%= @education.website %>
			</p>

			<p>
				<b>Location:</b>
				<%= @education.location %>
			</p>

			<p>
				<b>Start date:</b>
				<%= @education.start_date %>
			</p>

			<p>
				<b>End date:</b>
				<%= @education.end_date %>
			</p>

			<p>
				<b>Description:</b>
				<%= simple_format(@education.description) %>
			</p>

			<p>
				<b>Keywords:</b>
				<%= @education.keywords %>
			</p>

		</div>
		<div class="span7">
			<table class="table table-bordered">
				<caption>
					<h3>Linked Picture :</h3>
				</caption>
				<tr>
					<th>Legend</th>
					<th>Picture</th>
				</tr>
				<% @education.pictures.each do |picture| %>
				<tr>
					<td><%= picture.legend %></td>
					<td><%= image_tag(picture.url, :width => 50) if picture.url.present? %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>

	<%= link_to 'Edit', edit_education_path(@education), :class=>"btn btn-danger"  unless !logged_in? %>
	<%= link_to 'Back', educations_path, :class=>"btn" %>
</article>